apiVersion: vendir.k14s.io/v1alpha1
kind: Config

minimumRequiredVersion: 0.34.0
directories:
# doc: https://carvel.dev/vendir/docs/v0.35.x/vendir-spec/

- path: src/github.com
  contents:

  - path: derailed/k9s
    githubRelease:
      slug: derailed/k9s
      tag: v0.31.8
      disableAutoChecksumValidation: true
      assetNames: # only download specific assets (optional; v0.12.0+), see k3s declaration for details.
      - "k9s_Linux_amd64.tar.gz"


